### ISSUE TITLE
Latency issue with lambda log shippers - cloudtrail and  config

### ISSUE THREAD

**Issue by neisije** [digitc1/AWSLandingZone#104]
To improve the latency issue induced by lambda log shippers, the code of the lambda has been revised:

- to allow concurrent writing to cloudwatch loggroups to remove the throttling
- to write a batch of events logs instead of a single event log to cloudwatch loggroups to improve the performance, decrease the risk of having InvalidSequenceTokenException and possible timeout or failure to process a S3 object
- consequently improve the running cost

Lambdas were throttled by the setting allowing only 1 max concurrent execution. This max was set to tackle the client.exceptions.InvalidSequenceTokenException resulting in an unacceptable latency in splunk.

The source code of the updated lambdas is currently available in our devops account under:

- $HOME/AWSLandingZone/LAMBDAS/CloudtrailLogShipper.py 
- $HOME/AWSLandingZone/LAMBDAS/ConfigLogShipper.py 

The cloudformation was also adapted:

- a size limitation of inline zip code in CFT (max 4096 bytes)
- deploy a dynamodb table used by the lambda to store the nextSequenceToken of a cloudwatch loggroup
- update the role of the lambdas to allow the access to the dynamodb table
- increase the timeout of the lambdas from 600 to 900 (15 minutes which is the max allowed)
- add an additional environment parameter to set a maximum number of retry in case of client.exceptions.InvalidSequenceTokenException (default value 30 retries)
- set the concurrent execution of the lambdas to unlimited (max value 1000)
- set the runtime to python3.8 instead of python3.6

To deploy the new release of the lambda in DIGIT-C1-SECLOG account, the following command was executed:

`./EC-Update-SecLog.sh --organisation EC_BROKER_ADM --seclogprofile DIGIT-C1-SECLOG --splunkprofile EC_DIGIT_C2-SPLUNK --notificationemail joao-miguel.silva-da-silva@ext.ec.europa.eu --logdestination dgtest`

**NB:** 
To deploy a new release of the lambdas to a SECLOG account:

- the S3Key defined in the CFT must be changed. To solve this I've added a release number in the S3 Key.
- the zip files must be stored on a S3 bucket accessible by the SECLOG accounts before the update of the cloudformation template.

**Exemple:** 

```
    CloudTrailLogShipperFunction:
      Type: 'AWS::Lambda::Function'
      DependsOn:
        - DynamoDBTable
      Properties:
        Code:
          S3Bucket: "lambda-artifacts-0764bb79bbdcfde5"
          S3Key: "SLZ/1.3.2.1/CloudtrailLogShipper.zip"
        Handler: 'CloudtrailLogShipper.lambda_handler'
        MemorySize: 128
        Role: !GetAtt LogShipperLambdaExecutionRole.Arn
        Runtime: python3.8
        Timeout: 900
        Environment:
          Variables:
            LOG_LEVEL: !Ref lambdaLogLevel
            MAX_TRY: !Ref lambdaMaxRetry
```
